docs: Fix grammatical & typo errors in the README.md file.
a85/POSTMan-Chrome-Extension pull request #9099
Opened 2020-09-27 06:55 UTC by roubalsehgal

## Proposed changes
Resolved some typo & grammatical errors in the README file.

## Types of changes

- [x] Documentation Update (README file updated)

## Checklist

- [x] I have read the **CONTRIBUTION** guidelines.

2020-09-27 14:11 UTC, roubalsehgal commented
Hello reviewers,

I was just going through the README of this repo & just spotted this minor errors so thought of giving it a PR to make it better. Please let me know if it is a valid PR or not.

If not please share your feedback!

2020-10-01 10:17 UTC, arlemi requested changes
Only added one little comment, everything else looks good, thanks for having a look at it!

2020-10-01 10:17 UTC, arlemi commented on README.md
> +If you have issues or code contributions about the Postman legacy version, head over to the [postmanlabs/postman-chrome-extension-legacy](https://github.com/postmanlabs/postman-chrome-extension-legac
Can we keep pertaining here?

2020-10-01 14:37 UTC, roubalsehgal commented on README.md
> +If you have issues or code contributions about the Postman legacy version, head over to the [postmanlabs/postman-chrome-extension-legacy](https://github.com/postmanlabs/postman-chrome-extension-legac
Yes, sure! 😀

2020-10-08 12:52 UTC, arlemi approved these changes
Looks good, thanks a lot for the updates! 🥳

2020-10-08 12:52 UTC, merged